# Site settings
title: Jin-Hong Park
email: jinhon9.park_at_gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Postdoctoral researcher in Seoul National University, Korea
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jinhong-park.github.io" # the base hostname & protocol for your site
telegram_username: jinhon9_park
# twitter_username: jekyllrb
# orcid_username:  jekyll

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Postdoctoral researcher"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""